# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: eb7a979fba544eff96e772888f5fa953dae0c22745176427d12e78d7d57a2eb8ecd791f824a969ac23fe16cb032a817bd542b9366029ef627f2ebc2f4eceec09

test:
  secret_key_base: 4569c2148b5dc4a318f273d15629cd585c2b024b73da00586ace3a07d39f88ee28273417cbc15b3112c12cbdce73dc40d5932e99e07b952f5156da691f3071d4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
